### ISSUE TITLE
deploy tutorials on google app engine

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/computation#24]
the tutorials are likely going to be large enough that we want them deploying from travis to google app engine instead of through read the docs

**Comment by rowanc1** [comment]
I am going to point http://tutorials.simpeg.xyz to rtfd for now.

**Comment by rowanc1** [comment]
@lheagy I think you need to add something on the rtd side?

http://tutorials.simpeg.xyz/

**Comment by rowanc1** [comment]
![image](https://cloud.githubusercontent.com/assets/913249/18772419/fb616ab2-8103-11e6-8643-c5aa55a79e68.png)

**Comment by lheagy** [comment]
@rowanc1 : could you point it to `ghs.googlehosted.com`. I have started: http://simpegtutorials.appspot.com/ and we can point the app engine site (simpegtutorials, you should have edit access on this) to the simpeg domain. I would like to tear down readthedocs (it doesn't work well with the downloads, etc that we are starting to use)

**Comment by rowanc1** [comment]
Done. Might take a while to propagate.

**Comment by rowanc1** [comment]
Does this auto deploy?

**Comment by lheagy** [comment]
Awesome, thanks! Not yet, I will get that going tonight or tomorrow
